apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volumes
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claims
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi