apiVersion: v1
kind: ConfigMap  
metadata:
  name: web-config
data:
   DATABASE_ENGINE: django.db.backends.mysql
   DATABASE_NAME: mydb
   DATABASE_USER: user
   DATABASE_PASSWORD: password
   DATABASE_HOST: mysqlservice
   DATABASE_PORT: "3306"
  