
web:
   replicas: 3
   labels:
     name: myapp
   container:
     image:
       name: application
       pullPolicy: Never
     name: myapp
     port: 8000
   initcontainer:
     image:
       name: busybox:1.28
       
     name: initprocess
     command: "['sh', '-c', 'echo Waiting for db service ! && sleep 30']"

   service:
     type: ClusterIP
     port: 8000
     name: appservice   
   config:
     name: webconfig
     data:
          DATABASE_ENGINE: django.db.backends.mysql
          DATABASE_NAME: mydb
          DATABASE_USER: user
          DATABASE_PASSWORD: password
          DATABASE_HOST: mysqlservice 
          DATABASE_PORT: "3306"
  

db:
  replicas: 1
  
  labels:
    app: db
  container:
    name: database
    image:
       name: mariadb
    port: 3306
     
  service:
    protocol: TCP
    port: 3306

  config:
    name: dbconfig
    data:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE:  mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: password


ingress:
 
  hosts:
    name1: abc.com   
  service:
    svc1:
     name: appservice
     port: 8000
        