apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  #namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{.Values.ingress.hosts.name1}} #abc.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{.Values.ingress.service.svc1.name}} #appservice
            port:
              number: {{.Values.ingress.service.svc1.port}} 